## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [2]:
import numpy as np
import pandas as pd

In [3]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

In [4]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [36]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
temp = titanic_df.groupby('Pclass')

In [66]:
for group in list(temp.groups.keys()):
    print(f"Pclass {group}: Avg age {temp.get_group(group)['Age'].mean()} and total missing values {temp.get_group(group)['Age'].isna().sum()}")

Pclass 1: Avg age 38.233440860215055 and total missing values 30
Pclass 2: Avg age 29.87763005780347 and total missing values 11
Pclass 3: Avg age 25.14061971830986 and total missing values 136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [68]:
for group in list(temp.groups.keys()):
    mode = temp.get_group(group)['Embarked'].mode()
    temp.get_group(group)['Embarked'].fillna(mode)
    print(temp.get_group(group)['Embarked'].value_counts(ascending=True))

Embarked
Q      2
C     85
S    127
Name: count, dtype: int64
Embarked
Q      3
C     17
S    164
Name: count, dtype: int64
Embarked
C     66
Q     72
S    353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [74]:
titanic_df.groupby(['Embarked','Pclass'])['Fare'].mean()

Embarked  Pclass
C         1         104.718529
          2          25.358335
          3          11.214083
Q         1          90.000000
          2          12.350000
          3          11.183393
S         1          70.364862
          2          20.327439
          3          14.644083
Name: Fare, dtype: float64

In [80]:
my_dict = {}
embarked_groups = titanic_df.groupby(['Embarked'])
for embarked_group in list(embarked_groups.group.keys()):

SyntaxError: expected ':' (606791105.py, line 3)

In [140]:
np.round(titanic_df.groupby(['Embarked','Pclass'])['Fare'].mean(),2)

Embarked  Pclass
C         1         104.72
          2          25.36
          3          11.21
Q         1          90.00
          2          12.35
          3          11.18
S         1          70.36
          2          20.33
          3          14.64
Name: Fare, dtype: float64

In [136]:
titanic_df.groupby(['Embarked','Pclass'])['Fare'].mean().reset_index()

  Embarked  Pclass        Fare
0        C       1  104.718529
1        C       2   25.358335
2        C       3   11.214083
3        Q       1   90.000000
4        Q       2   12.350000
5        Q       3   11.183393
6        S       1   70.364862
7        S       2   20.327439
8        S       3   14.644083

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [143]:
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [150]:
fifa_df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [152]:
team = fifa_df.groupby('Team')

In [154]:
def z_normalization(group,col_to_perform):
    L = []
    for i in col_to_perform:
       L.append((group[i] - group[i].mean())/group[i].std())
    return L

In [160]:
team.apply(z_normalization,['Passes','Passes Completed','Crosses','Crosses Completed'])

C:\Users\vikas\AppData\Local\Temp\ipykernel_25252\3028069025.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  team.apply(z_normalization,['Passes','Passes Completed','Crosses','Crosses Completed'])

Team
Argentina         [[-0.2081379482131027, -0.6304468286454852, 1....
Australia         [[0.9327822981462446, -0.5687696939916126, -1....
Belgium           [[-1.0826957835703472, 0.888950222299864, 0.19...
Brazil            [[-0.29005638991957045, -0.6353616160142981, -...
Cameroon          [[1.0897127288785045, -0.21410777957436866, -0...
Canada            [[-1.1208970766356094, 0.32025630761017465, 0....
Costa Rica        [[-1.0131779033236277, 0.9862793749168057, 0.0...
Croatia           [[0.5726577201720259, -1.441280367836805, -0.2...
Denmark           [[0.0999187841685248, -1.0462084459998555, 0.9...
Ecuador           [[1.0858755590513685, -0.8830196853824327, -0....
England           [[1.7058443670113492, -0.5184261215691465, -0....
France            [[1.571018948298315, -0.14310901350895622, 0.8...
Germany           [[0.7653920744856799, -1.131449153587527, 0.36...
Ghana             [[0.09892572557806385, -1.0457862418252464, 0....
Iran              [[-0.8206945344647688, -0.2931051908802746, 1....
Japan             [[-0.7091552607979986, 0.9798252076674637, -1....
Korea Republic    [[-0.5116407999333112, 0.7916968167389132, -1....
Mexico            [[1.0653416196374352, -0.9183979479633066, -0....
Morocco           [[-0.2139245272030895, -0.4635031422733608, 0....
Netherlands       [[-0.7020292511550764, -0.2292604750082075, 1....
Poland            [[-0.33401691183799054, -0.6947551766230203, -...
Portugal          [[0.44244085488167306, 0.022245629575055655, 0...
Qatar             [[0.4627249968907184, -1.1475579922889854, 0.6...
Saudi Arabia      [[-0.6678958810165907, 1.1496907425548741, -0....
Senegal           [[-0.020933516060466586, 1.2350774475675286, -...
Serbia            [[-1.0898071115461836, 0.87541882730759, 0.214...
Spain             [[0.48664140696137753, -1.4987584478735692, 0....
Switzerland       [[0.4488861225754249, 0.26525089061275103, -1....
Tunisia           [[-0.06540542071358316, 1.0310972206611897, -0...
United States     [[0.8195405702879763, -1.1363377655253455, -0....
Uruguay           [[1.056569517673894, -0.9317022110397071, -0.1...
Wales             [[-0.054583721675151284, 1.0261739674928443, -...
dtype: object

In [181]:
# team['Passes'].min()
# team['Passes'].max()
# team['Yellow Cards'].min()
# team['Yellow Cards'].max()
# team['Yellow Cards'].mean()
# team['Crosses'].min()
# team['Crosses'].max()
# team['Crosses'].std()
team['Possession (%)'].mean()

Team
Argentina         49.285714
Australia         31.250000
Belgium           49.000000
Brazil            50.400000
Cameroon          38.333333
Canada            44.333333
Costa Rica        27.333333
Croatia           47.428571
Denmark           51.333333
Ecuador           42.666667
England           57.200000
France            44.857143
Germany           53.000000
Ghana             37.000000
Iran              31.666667
Japan             30.250000
Korea Republic    42.250000
Mexico            46.666667
Morocco           34.285714
Netherlands       44.000000
Poland            32.000000
Portugal          53.800000
Qatar             39.333333
Saudi Arabia      36.666667
Senegal           38.500000
Serbia            42.666667
Spain             67.000000
Switzerland       43.000000
Tunisia           38.666667
United States     47.000000
Uruguay           41.000000
Wales             41.000000
Name: Possession (%), dtype: float64

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

### `Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [193]:
ipl = pd.read_csv('ipl_deliveries.csv')
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

### `Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

### `Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

### `Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.